"""Broker-email builder — renders generated bond/loan payloads as broker-style
HTML emails that mirror the Genesis Email Parsing POC samples.

The engines already build a full ``DETAILS`` dict per tranche; this module just
re-renders that same data as the natural-language / labelled-block emails that
banks send, so the Genesis email-parsing pipeline can be fed synthetic mail.

Fields that the payload generators do not produce (Call Protection, Non-Call
period, First Reset date, free-text business/UoP prose, …) are filled two ways:

* **Boilerplate** — a fixed canned string, identical on every email
  (see ``_BOILERPLATE``).
* **Random pool** — one value picked from a small realistic list each time
  (see ``_POOLS`` and ``_pick``).

No external dependencies and no network — pure string building, so it is unit
testable without Outlook or credentials.

``build_email`` also reports **what it actually rendered** (spec §18.6): a set
of canonical field names (app column names, so the comparator can intersect
them with ``field_map.csv``) plus the gap-fill values it picked. A field the
generator produced but the chosen format never printed cannot be extracted by
the email-parsing agent, so scoring it would understate accuracy; and a value
the *template* invented (the use-of-proceeds prose, the ``T+n`` label, the
rating outlook) is only knowable here, so the expectation writer needs it back.
"""
from __future__ import annotations

import random
import re
import threading
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

# ── formats ────────────────────────────────────────────────────────────────
# id -> (human label, tool). Exposed to the UI via routers/config, but the
# frontend hardcodes the same list, so this is the authoritative reference.
# Five distinct *structural* layouts modelled on the Genesis POC bond samples
# (Format 1-10). Each renders whatever the generator produced (1..N tranches)
# faithfully; they differ in layout, not deal type.
BOND_FORMATS = {
    "bond_stacked": "Stacked labelled block — deal header + per-tranche table (Oracle/SpaceX)",
    "bond_single": "Single labelled block (Synchrony/PSNH style)",
    "bond_colon": "Compact colon-inline, per-tenor blocks (Amazon CAD)",
    "bond_inline": "Inline single-line rows + IPTs header (SMBC)",
    "bond_narrative": "Investor-call narrative + stacked table (SpaceX)",
}
LOAN_FORMATS = {
    "loan_jpm": "JPM Loan Launch (COMPANY/BORROWER/BUSINESS/UOP)",
    "loan_barclays": "Barclays Lead Left / Calendar (Borrower/Facility + Commitments Due)",
    "loan_citi": "Citi Loan (Borrower/Facility)",
    "loan_rbc": "RBC Debut TLB (narrative + Business/Sponsor/Ratings)",
}

DEFAULT_BOND_FORMAT = "bond_stacked"
DEFAULT_LOAN_FORMAT = "loan_jpm"


# ── boilerplate (fixed) & random pools ───────────────────────────────────────

_BOILERPLATE = {
    # identical on every generated email
    "listing": "Luxembourg Stock Exchange's Euro MTF Market",
    "denominations": "2,000 x 1,000",
    "governing_law": "New York law",
    "timing": "Today's Business",
    "disclaimer": (
        "This message is generated by the PBI Test Utility for parser testing "
        "only and does not constitute an offer to sell or a solicitation of an "
        "offer to buy any security."
    ),
}

# Generic placeholder signature (NOT a real person — per the user's choice).
_SIGNATURE_LINES = [
    "PBI Test Desk",
    "Data Insertion Console",
    "Genesis Global — TrOWE (test environment)",
]

_POOLS = {
    "call_protection": [
        "101 soft call for 6 months",
        "101 soft call for 12 months",
        "NC1, then 102 / 101",
        "Non-call life",
    ],
    "non_call": ["3-Years", "5-Years", "5NC2", "6NC3"],
    "oid_talk": ["99.0", "99.5", "99.5-99.75", "TBD"],
    "floor": ["0.00% floor", "0.50% floor", "0.75% floor"],
    "business_bond": [
        "a leading global issuer with a diversified revenue base across core markets",
        "a well-capitalised institution with investment-grade fundamentals",
        "a market leader in its sector with stable, contracted cash flows",
    ],
    "settlement_note": ["T+3", "T+5", "T+2"],
    # bond gap-fill pools (fields the generator does not produce)
    "optional_redemption": [
        "Make Whole Call | Par Call: 1 month(s) prior to maturity",
        "Make Whole Call | Par Call: 2 month(s) prior to maturity",
        "Make Whole Call | Par Call: 3 month(s) prior to maturity",
        "Make Whole Call | Par Call: 6 month(s) prior to maturity",
    ],
    "ranking": ["Sr Unsecured Note", "Senior Bank Note", "1st Mtge Bond",
                "Subordinated Note", "Senior Secured Note"],
    "uop_bond": [
        "General Corporate Purposes",
        "The net proceeds of this offering will be used for general corporate "
        "purposes, which may include capital expenditures and repayment of indebtedness.",
        "To refinance short-term debt and fund capital expenditures and working capital",
    ],
    "canada": ["Yes - Exemption", "Yes - Wrapper", "No"],
    "settle_days": ["T+2", "T+3", "T+5"],
}


# ── render recording (spec §18.6) ────────────────────────────────────────────
# Renderers declare the canonical fields they printed and the gap-fill values
# they picked. The recorder is thread-local because engines render on their own
# background thread, and is only live for the duration of one build_email call.

# Which app column a gap-fill pool ends up populating.
_POOL_FIELDS: Dict[str, Tuple[str, ...]] = {
    "uop_bond": ("use_of_proceeds",),
    "optional_redemption": ("call_indicator",),
    "business_bond": ("tranche_issuer_business_description",),
}

_state = threading.local()


class _Recorder:
    def __init__(self) -> None:
        self.fields: set[str] = set()
        self.gap: Dict[str, Any] = {}

    def mark(self, *names: str) -> None:
        self.fields.update(n for n in names if n)

    def append(self, key: str, value: Any) -> None:
        self.gap.setdefault(key, []).append(value)

    def meta(self) -> Dict[str, Any]:
        return {"rendered_fields": sorted(self.fields), "gap_fill": dict(self.gap)}


def _rec() -> Optional[_Recorder]:
    return getattr(_state, "rec", None)


def _mark(*names: str) -> None:
    r = _rec()
    if r is not None:
        r.mark(*names)


def _pick(pool: str) -> str:
    value = random.choice(_POOLS[pool])
    r = _rec()
    if r is not None:
        r.append(pool, value)
        r.mark(*_POOL_FIELDS.get(pool, ()))
    return value


# ── formatting helpers ───────────────────────────────────────────────────────

def _epoch_to_dt(value: Any) -> datetime | None:
    """Accept epoch-ms (int or str) and return a UTC datetime, else None."""
    if value is None:
        return None
    try:
        ms = int(str(value))
    except (TypeError, ValueError):
        return None
    if ms <= 0:
        return None
    try:
        return datetime.fromtimestamp(ms / 1000, tz=timezone.utc)
    except (OverflowError, OSError, ValueError):
        return None


def _month_year(value: Any) -> str:
    dt = _epoch_to_dt(value)
    return dt.strftime("%B %Y") if dt else "TBA"


def _long_date(value: Any) -> str:
    dt = _epoch_to_dt(value)
    return dt.strftime("%A, %B %d, %Y") if dt else "TBA"


def _short_date(value: Any) -> str:
    """Epoch-ms -> 'Feb 04, 2029' (the format used in the bond samples)."""
    dt = _epoch_to_dt(value)
    return dt.strftime("%b %d, %Y") if dt else "TBA"


def _settlement(det: Dict[str, Any]) -> str:
    """'T+3 (Jun 26, 2026)' from TRANCHE_SETTLEMENT_DATE + a random T+n label."""
    d = _short_date(det.get("TRANCHE_SETTLEMENT_DATE"))
    label = _pick("settle_days")
    r = _rec()
    if r is not None:
        m = re.search(r"T\+(\d+)", label)
        if m:
            r.append("settlement_period", int(m.group(1)))
            r.mark("tranche_settlement_period")
        if d != "TBA":
            r.mark("tranche_settlement_date")
    return f"{label} ({d})" if d != "TBA" else label


def _size_line(det: Dict[str, Any]) -> str:
    """Real samples usually say 'USD Benchmark'; show the real amount when present."""
    amt = det.get("TOTAL_ISSUED_AMOUNT")
    ccy = det.get("CURRENCY_CODE", "")
    _mark("currency_code", "tranche_currency")
    if amt:
        _mark("total_issued_amount")
        return f"{ccy} {_fmt_amount(amt, ccy)}".strip()
    return f"{ccy} Benchmark".strip() or "Benchmark"


def _tenor_words(det: Dict[str, Any]) -> str:
    """'10Y' -> '10 Year' (samples spell it out); pass through if already words."""
    t = str(det.get("PRELIMINARY_SECURITY_TENOR", "") or "")
    if t:
        _mark("preliminary_security_tenor", "tenor", "years_to_maturity")
    m = re.fullmatch(r"(\d+(?:\.\d+)?)Y", t.strip(), re.I)
    return f"{m.group(1)} Year" if m else t


def _cusip_of(det: Dict[str, Any]) -> str:
    for k in ("SEC_144A_CUSIP", "SEC_REGS_CUSIP"):
        if det.get(k):
            _mark(k.lower(), "cusip")
            return det[k]
    return ""


def _isin_of(det: Dict[str, Any]) -> str:
    for k in ("SEC_144A_ISIN", "SEC_REGS_ISIN"):
        if det.get(k):
            _mark(k.lower(), "isin")
            return det[k]
    return ""


def _td_lead(note: str) -> str:
    """The 'TD <date> – <note>' desk lead line the samples open with."""
    return f'<p style="margin-bottom:12px;">TD — {_esc(note)}</p>'


def _signature_html() -> str:
    lines = "<br>".join(_esc(x) for x in _SIGNATURE_LINES)
    return (f'<p style="margin-top:18px;color:#555;font-size:10pt;">{lines}</p>'
            f'<p style="margin-top:8px;color:#888;font-size:8.5pt;">'
            f'{_esc(_BOILERPLATE["disclaimer"])}</p>')


def _fmt_amount(value: Any, currency: str = "") -> str:
    """750000000 -> '750mm' (or '$750mm' with a currency symbol prefix)."""
    try:
        n = float(value)
    except (TypeError, ValueError):
        return str(value)
    sym = {"USD": "$", "EUR": "€", "GBP": "£"}.get((currency or "").upper(), "")
    if n >= 1_000_000_000:
        body = f"{n / 1_000_000_000:.2f}".rstrip("0").rstrip(".") + "bn"
    elif n >= 1_000_000:
        body = f"{n / 1_000_000:.0f}mm"
    else:
        body = f"{n:,.0f}"
    return f"{sym}{body}"


def _esc(text: Any) -> str:
    s = "" if text is None else str(text)
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _labelled_html(title: str, rows: List[Tuple[str, str]], footer: str = "") -> str:
    """Render a labelled vertical block: bolded label then value, as the desk
    forwards do. Values already HTML-escaped by the caller where needed."""
    parts = [
        '<div style="font-family:Calibri,Arial,sans-serif;font-size:11pt;color:#1a1a1a;">',
        f'<p style="font-weight:bold;font-size:12pt;">{_esc(title)}</p>',
    ]
    for label, value in rows:
        if value is None or value == "":
            continue
        parts.append(
            f'<p style="margin:6px 0 0 0;"><b>{_esc(label)}</b><br>{value}</p>'
        )
    if footer:
        parts.append(
            f'<p style="margin-top:14px;color:#666;font-size:9pt;">{_esc(footer)}</p>'
        )
    parts.append("</div>")
    return "\n".join(parts)


# ── ratings helpers ──────────────────────────────────────────────────────────

def _bond_ratings_rows(det: Dict[str, Any]) -> str:
    """Bonds carry a single combined ISSUER_RATING like 'Baa2/BBB/BBB-'."""
    combined = det.get("ISSUER_RATING") or ""
    parts = [p.strip() for p in combined.split("/") if p.strip()]
    agencies = ["Moody's", "S&P", "Fitch"]
    lines = []
    for i, agency in enumerate(agencies):
        if i < len(parts):
            lines.append(f"{agency} (Exp): {_esc(parts[i])}/Stable")
    if combined:
        # The outlook is glued onto each rating here and split back out into its
        # own column by expected_writer — see spec §18.6.1.
        _mark("issuer_rating", "rating_outlook")
        r = _rec()
        if r is not None and lines:
            r.gap["rating_outlook"] = "Stable"
    return "<br>".join(lines) if lines else _esc(combined)


def _loan_ratings(det: Dict[str, Any]) -> str:
    m = det.get("ISSUER_MOODYS") or det.get("TRANCHE_MOODYS") or ""
    s = det.get("ISSUER_SP") or det.get("TRANCHE_SP") or ""
    f = det.get("ISSUER_FITCH") or det.get("TRANCHE_FITCH") or ""
    return f"{_esc(m)} (Moody's) / {_esc(s)} (S&P) / {_esc(f)} (Fitch)"


# ── BOND emails ──────────────────────────────────────────────────────────────

_WRAP_OPEN = ('<div style="font-family:Calibri,Arial,sans-serif;'
              'font-size:11pt;color:#1a1a1a;line-height:1.5;">')
_WRAP_CLOSE = "</div>"


def _deal_header_rows(d0: Dict[str, Any], dets: List[Dict[str, Any]]) -> List[Tuple[str, str]]:
    """Deal-level labelled rows shared by the stacked / narrative formats."""
    _mark("issuer_name", "issuer_ticker", "registration_type", "tranche_reg_type",
          "bookrunners")
    return [
        ("Issuer/Ticker", f"{_esc(d0.get('ISSUER_NAME'))} ( {_esc(d0.get('ISSUER_TICKER'))} )"),
        ("Ratings", _bond_ratings_rows(d0)),
        ("Format", _esc(d0.get("REGISTRATION_TYPE"))),
        ("Ranking", _pick("ranking")),                    # gap: random pool
        ("Total Size", _size_line(d0)),
        ("Book Runner(s)", "Active: " + _esc(d0.get("BOOKRUNNERS"))),
        ("Use of Proceeds", _pick("uop_bond")),           # gap: random pool
        ("Denominations", _BOILERPLATE["denominations"]),  # gap: boilerplate
        ("Settlement", _settlement(d0)),
        ("Timing", _BOILERPLATE["timing"]),               # gap: boilerplate
        ("Sale into Canada", _pick("canada")),            # gap: random pool
    ]


def _kv_block(rows: List[Tuple[str, str]]) -> str:
    out = []
    for label, value in rows:
        if value in (None, ""):
            continue
        out.append(f'<p style="margin:6px 0 0 0;"><b>{_esc(label)}</b><br>{value}</p>')
    return "\n".join(out)


def _tranche_table(dets: List[Dict[str, Any]]) -> str:
    """Per-tranche fields as label | T1 | T2 | … (mirrors the stacked samples)."""
    hdr = "".join(f"<th style='padding:4px 12px;text-align:left;border-bottom:1px solid #ccc;'>"
                  f"T{i+1}</th>" for i in range(len(dets)))

    def row(label, fn):
        cells = "".join(f"<td style='padding:4px 12px;vertical-align:top;'>{fn(d)}</td>"
                        for d in dets)
        return (f"<tr><td style='padding:4px 12px;font-weight:bold;vertical-align:top;'>"
                f"{_esc(label)}</td>{cells}</tr>")

    _mark("coupon_type", "ipts", "maturity_date")
    body = "\n".join([
        row("Tenor", lambda d: _esc(_tenor_words(d))),
        row("Tranche Size", lambda d: _size_line(d)),
        row("Coupon Type", lambda d: _esc(d.get("COUPON_TYPE"))),
        row("IPT", lambda d: _esc(d.get("IPTS"))),
        row("Maturity Date", lambda d: _short_date(d.get("MATURITY_DATE"))),
        row("Optional Redemption", lambda d: _esc(_pick("optional_redemption"))),
        row("Cusip", lambda d: _esc(_cusip_of(d))),
        row("ISIN", lambda d: _esc(_isin_of(d))),
    ])
    return ("<table style='border-collapse:collapse;margin-top:12px;font-size:10.5pt;'>"
            f"<tr><td></td>{hdr}</tr>{body}</table>")


def build_bond_email(tranches: List[Dict[str, Any]], fmt: str) -> Tuple[str, str]:
    """tranches: list of full payloads. One email per deal (1..N tranches)."""
    dets = [t["DETAILS"] for t in tranches]
    if fmt == "bond_single":
        return _bond_single(dets)
    if fmt == "bond_colon":
        return _bond_colon(dets)
    if fmt == "bond_inline":
        return _bond_inline(dets)
    if fmt == "bond_narrative":
        return _bond_narrative(dets)
    return _bond_stacked(dets)  # default


def _bond_stacked(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    """Deal-level labelled header + per-tranche table (Format 1/2/7/9)."""
    d0 = dets[0]
    issuer, ticker = d0.get("ISSUER_NAME", "Issuer"), d0.get("ISSUER_TICKER", "")
    subject = f"[EXTERNAL] New Issue — {issuer} ( {ticker} )"
    note = f"{issuer} new issue, {len(dets)} tranche(s)"
    body = (_WRAP_OPEN + _td_lead(note)
            + _kv_block(_deal_header_rows(d0, dets))
            + _tranche_table(dets)
            + _signature_html() + _WRAP_CLOSE)
    return subject, body


def _bond_single(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    """Single labelled block per tranche (Format 3/6). Deal + tranche fields inline."""
    d0 = dets[0]
    issuer, ticker = d0.get("ISSUER_NAME", "Issuer"), d0.get("ISSUER_TICKER", "")
    subject = f"[EXTERNAL] New Issue — {issuer} ( {ticker} )"
    _mark("coupon_type", "ipts", "maturity_date")
    blocks = []
    for i, d in enumerate(dets):
        rows = _deal_header_rows(d, [d]) + [
            ("Tenor", _tenor_words(d)),
            ("IPT", _esc(d.get("IPTS"))),
            ("Coupon Type", _esc(d.get("COUPON_TYPE"))),
            ("Maturity Date", _short_date(d.get("MATURITY_DATE"))),
            ("Optional Redemption", _esc(_pick("optional_redemption"))),
            ("Cusip", _esc(_cusip_of(d))),
            ("ISIN", _esc(_isin_of(d))),
        ]
        head = "" if len(dets) == 1 else f'<p style="font-weight:bold;margin-top:14px;">Tranche {i+1}</p>'
        blocks.append(head + _kv_block(rows))
    body = _WRAP_OPEN + _td_lead(f"{issuer} new issue") + "\n".join(blocks) + _signature_html() + _WRAP_CLOSE
    return subject, body


def _bond_colon(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    """Compact 'Label: value' with a repeated per-tenor block (Format 4, Amazon CAD)."""
    d0 = dets[0]
    issuer, ticker = d0.get("ISSUER_NAME", "Issuer"), d0.get("ISSUER_TICKER", "")
    ccy = d0.get("CURRENCY_CODE", "")
    tenors = "s-".join(_tenor_words(d).split(" ")[0] for d in dets) + "s" if len(dets) > 1 else _tenor_words(d0)
    subject = f"Fwd: ** NEW ISSUE ** {issuer} {ccy} {tenors}"
    # This format prints no security identifiers, so row matching falls through
    # to the ticker-based keys (spec §18.7) — hence the Issuer line below, which
    # every matching key needs. Without it a faithfully-extracted deal cannot be
    # matched to its expectation at all.
    _mark("issuer_name", "issuer_ticker", "bookrunners", "tranche_settlement_date",
          "maturity_date", "ipts", "coupon_type")

    head = [
        f"<b>Issuer:</b> {_esc(issuer)} ( {_esc(ticker)} )",
        f"<b>Syndicate:</b> {_esc(d0.get('BOOKRUNNERS'))}",
        f"<b>Pricing:</b> {_short_date(d0.get('TRANCHE_SETTLEMENT_DATE'))}",
        f"<b>Settlement:</b> {_settlement(d0)}",
    ]
    blocks = []
    for d in dets:
        blocks.append("<br>".join([
            f"<b>Tenor:</b> {_esc(_tenor_words(d))}",
            f"<b>Size:</b> {_size_line(d)}",
            f"<b>Maturity:</b> {_short_date(d.get('MATURITY_DATE'))}",
            f"<b>Spread to Curve:</b> {_esc(d.get('IPTS'))}",
            f"<b>Coupon Type:</b> {_esc(d.get('COUPON_TYPE'))}",
        ]))
    body = (_WRAP_OPEN
            + "<p>" + "<br>".join(head) + "</p>"
            + "".join(f'<p style="margin-top:10px;">{b}</p>' for b in blocks)
            + _signature_html() + _WRAP_CLOSE)
    return subject, body


def _bond_inline(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    """Inline single-line rows + IPTs header (Format 8, SMBC 'messy formatting')."""
    d0 = dets[0]
    issuer, ticker = d0.get("ISSUER_NAME", "Issuer"), d0.get("ISSUER_TICKER", "")
    subject = f"[EXTERNAL] *** IPTs: {issuer} ({ticker}) ***"
    _mark("issuer_name", "issuer_ticker", "registration_type", "tranche_reg_type",
          "bookrunners", "coupon_type", "ipts", "maturity_date")

    ipt_lines = "<br>".join(
        f"{_esc(_tenor_words(d))} {_esc(d.get('COUPON_TYPE'))}: {_esc(d.get('IPTS'))}"
        for d in dets)

    def joined(fn):
        return " ".join(_esc(fn(d)) for d in dets)

    rows = [
        f"<b>Issuer/Ticker</b> {_esc(issuer)} ( {_esc(ticker)} )",
        f"<b>Format</b> {_esc(d0.get('REGISTRATION_TYPE'))}",
        f"<b>Total Size</b> {_size_line(d0)}",
        f"<b>Ranking</b> {_esc(_pick('ranking'))}",
        f"<b>Issuer Ratings</b> {_bond_ratings_inline(d0)}",
        f"<b>Tenor</b> {joined(_tenor_words)}",
        f"<b>Coupon Type</b> {joined(lambda d: d.get('COUPON_TYPE'))}",
        f"<b>Maturity Date</b> {joined(lambda d: _short_date(d.get('MATURITY_DATE')))}",
        f"<b>Book Runner(s)</b> Active: {_esc(d0.get('BOOKRUNNERS'))}",
        f"<b>Use of Proceeds</b> {_pick('uop_bond')}",
        f"<b>Denominations</b> {_BOILERPLATE['denominations']}",
        f"<b>Settlement</b> {_settlement(d0)}",
        f"<b>Cusip</b> {joined(_cusip_of)}",
        f"<b>ISIN</b> {joined(_isin_of)}",
    ]
    body = (_WRAP_OPEN
            + f'<p><b>*** IPTs: {_esc(issuer)} ({_esc(ticker)}) ***</b></p>'
            + f"<p>{ipt_lines}</p>"
            + "".join(f'<p style="margin:2px 0;">{r}</p>' for r in rows)
            + _signature_html() + _WRAP_CLOSE)
    return subject, body


def _bond_narrative(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    """Investor-call / mandate narrative followed by the stacked table (Format 7)."""
    d0 = dets[0]
    issuer, ticker = d0.get("ISSUER_NAME", "Issuer"), d0.get("ISSUER_TICKER", "")
    ccy = d0.get("CURRENCY_CODE", "")
    reg = d0.get("REGISTRATION_TYPE", "senior unsecured")
    tenors = ", ".join(_tenor_words(d).split(" ")[0] for d in dets)
    subject = f'[EXTERNAL] *** {issuer} ("{ticker}") | Fixed Income Investor Calls ***'
    _mark("issuer_name", "issuer_ticker", "bookrunners", "currency_code",
          "tranche_currency")
    narrative = (
        f'<p><b>*** {_esc(issuer)} ("{_esc(ticker)}") | Fixed Income Investor Calls ***</b></p>'
        f'<p>{_esc(issuer)} ("{_esc(ticker)}"), rated {_bond_ratings_inline(d0)}, has mandated '
        f'{_esc(d0.get("BOOKRUNNERS"))} to arrange fixed income investor calls to be held today.</p>'
        f'<p>A potential offering of {_esc(reg)} notes across {_esc(tenors)}yr '
        f'{_esc(ccy)}-denominated tenors is expected to follow, subject to market conditions.</p>'
        '<p>An electronic presentation and preliminary offering memorandum have been made available.</p>'
        '<p><b>Deal Announced</b></p>'
    )
    body = (_WRAP_OPEN + narrative
            + _kv_block(_deal_header_rows(d0, dets))
            + _tranche_table(dets)
            + _signature_html() + _WRAP_CLOSE)
    return subject, body


def _bond_ratings_inline(det: Dict[str, Any]) -> str:
    """'Baa1 (Moody's) / A- (S&P) / A- (Fitch)' from the combined ISSUER_RATING."""
    parts = [p.strip() for p in (det.get("ISSUER_RATING") or "").split("/") if p.strip()]
    if parts:
        _mark("issuer_rating")      # no outlook in this rendering
    ag = ["Moody's", "S&P", "Fitch"]
    return " / ".join(f"{_esc(parts[i])} ({ag[i]})" for i in range(min(len(parts), 3)))


# ── LOAN emails ──────────────────────────────────────────────────────────────

def _loan_facility(det: Dict[str, Any]) -> str:
    size = _fmt_amount(det.get("ISSUE_SIZE"), det.get("TRANCHE_CURRENCY", ""))
    seniority = det.get("BOND_SENIORITY", "Term Loan")
    return f"{size} {seniority} Term Loan B ({det.get('TENOR', '')})"


def _loan_margin(det: Dict[str, Any]) -> str:
    spread = det.get("SPREAD") or det.get("FINAL_SPREAD") or "TBD"
    ccy = (det.get("TRANCHE_CURRENCY") or "").upper()
    base = "E+" if ccy == "EUR" else "S+"
    return f"{base}{spread}bps / {_pick('floor')} / {_pick('oid_talk')} OID"


def build_loan_email(deal_payloads: List[Dict[str, Any]], fmt: str) -> Tuple[str, str]:
    """deal_payloads: all tranche payloads for ONE loan deal. One email per deal."""
    dets = [p["DETAILS"] for p in deal_payloads]
    d0 = dets[0]
    borrower = d0.get("ISSUER_NAME", "Borrower")
    ticker = d0.get("ISSUER_TICKER", "")

    if fmt == "loan_barclays":
        return _loan_barclays(dets)
    if fmt == "loan_citi":
        return _loan_citi(dets)
    if fmt == "loan_rbc":
        return _loan_rbc(dets)
    return _loan_jpm(dets)  # default


def _loan_facilities_block(dets: List[Dict[str, Any]]) -> str:
    return "<br>".join(_loan_facility(d) for d in dets)


def _loan_jpm(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    d0 = dets[0]
    borrower = d0.get("ISSUER_NAME", "Borrower")
    ticker = d0.get("ISSUER_TICKER", "")
    subject = f"[EXTERNAL] **** JPM LOAN LAUNCH: {borrower} ({ticker}) ****"
    rows = [
        ("COMPANY:", _esc(borrower)),
        ("BORROWER:", _esc(borrower)),
        ("SPONSOR:", _esc(d0.get("SPONSOR"))),
        ("BUSINESS:", _esc(d0.get("ISSUER_BUSINESS_DESCRIPTION")
                           or _pick("business_bond"))),
        ("FACILITY:", _loan_facilities_block(dets)),
        ("MARGIN GUIDANCE:", _loan_margin(d0)),
        ("CALL PROTECTION:", _pick("call_protection")),   # random pool
        ("UOP:", _esc(d0.get("USE_OF_PROCEEDS"))),
        ("EXPECTED RATINGS:", _loan_ratings(d0)),
        ("MATURITY:", _month_year(d0.get("MATURITY_DATE"))),
        ("COMMITMENTS DUE:", _long_date(d0.get("COMMIT_DATE"))),
        ("BOOKRUNNERS:", _esc(d0.get("BOOK_RUNNERS"))),
    ]
    return subject, _labelled_html(f"JPM LOAN LAUNCH — {borrower}", rows,
                                   _BOILERPLATE["disclaimer"])


def _loan_barclays(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    d0 = dets[0]
    borrower = d0.get("ISSUER_NAME", "Borrower")
    subject = f"[EXTERNAL] *** NEW BARC LEAD LEFT TERM LOAN: {borrower} ***"
    commit = _long_date(d0.get("COMMIT_DATE"))
    rows = [
        ("Borrower:", _esc(borrower)),
        ("Sponsor:", _esc(d0.get("SPONSOR"))),
        ("Facility:", _loan_facilities_block(dets)),
        ("Margin:", _loan_margin(d0)),
        ("Call Protection:", _pick("call_protection")),
        ("UOP:", _esc(d0.get("USE_OF_PROCEEDS"))),
        ("Ratings:", _loan_ratings(d0)),
        ("Maturity:", _month_year(d0.get("MATURITY_DATE"))),
        ("Bookrunners:", _esc(d0.get("BOOK_RUNNERS"))),
    ]
    footer = (f"*** COMMITMENTS DUE {commit.upper()} at 12:00pm ET ***  |  "
              "Use the Recommend Colleagues button at the top of the SyndTrak site")
    return subject, _labelled_html(f"BARCLAYS LEAD LEFT — {borrower}", rows, footer)


def _loan_citi(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    d0 = dets[0]
    borrower = d0.get("ISSUER_NAME", "Borrower")
    status = "Priced" if (d0.get("LOAN_STATUS") == "ACTIVE") else "Launched"
    subject = f"[EXTERNAL] *** New Citi Loan: {borrower} - {status} ***"
    rows = [
        ("Borrower:", _esc(borrower)),
        ("Facility:", _loan_facilities_block(dets)),
        ("Sponsor:", _esc(d0.get("SPONSOR"))),
        ("Margin:", _loan_margin(d0)),
        ("Call Protection:", _pick("call_protection")),
        ("UOP:", _esc(d0.get("USE_OF_PROCEEDS"))),
        ("Ratings:", _loan_ratings(d0)),
        ("Maturity:", _month_year(d0.get("MATURITY_DATE"))),
        ("Commitments Due:", _long_date(d0.get("COMMIT_DATE"))),
    ]
    return subject, _labelled_html(f"New Citi Loan — {borrower}", rows,
                                   _BOILERPLATE["disclaimer"])


def _loan_rbc(dets: List[Dict[str, Any]]) -> Tuple[str, str]:
    d0 = dets[0]
    borrower = d0.get("ISSUER_NAME", "Borrower")
    ccy = (d0.get("TRANCHE_CURRENCY") or "").upper()
    size = _fmt_amount(d0.get("ISSUE_SIZE"), ccy)
    subject = f"[EXTERNAL] *** NEW RBC DEBUT {ccy} TLB: {borrower} ***"
    narrative = (
        f"{size} {ccy} Term Loan B. Margin guidance is at {_loan_margin(d0)}. "
        f"Commitments are due by {_long_date(d0.get('COMMIT_DATE'))}."
    )
    rows = [
        ("Borrower:", _esc(borrower)),
        ("Business:", _esc(d0.get("ISSUER_BUSINESS_DESCRIPTION")
                           or _pick("business_bond"))),
        ("Sponsor:", _esc(d0.get("SPONSOR"))),
        ("Expected Corporate Ratings (S/M/F):", _loan_ratings(d0)),
        ("Facility:", _loan_facilities_block(dets)),
        ("UoP:", _esc(d0.get("USE_OF_PROCEEDS"))),
        ("Maturity:", _month_year(d0.get("MATURITY_DATE"))),
    ]
    body = (
        '<div style="font-family:Calibri,Arial,sans-serif;font-size:11pt;color:#1a1a1a;">'
        f'<p>{_esc(narrative)}</p>'
        + _labelled_html(f"RBC DEBUT {ccy} TLB — {borrower}", rows,
                         _BOILERPLATE["disclaimer"]).replace(
            '<div style="font-family:Calibri,Arial,sans-serif;font-size:11pt;color:#1a1a1a;">', '')
    )
    return subject, body


# ── dispatch ─────────────────────────────────────────────────────────────────

def build_email(tool: str, payloads: List[Dict[str, Any]],
                fmt: str) -> Tuple[str, str, Dict[str, Any]]:
    """tool: 'bonds' | 'loans'. payloads: all tranche payloads for one deal.

    Returns ``(subject, body_html, meta)`` where ``meta`` is::

        {"rendered_fields": [app column names the format actually printed],
         "gap_fill": {pool name -> [picks, in render order],
                      "settlement_period": [n, ...],
                      "rating_outlook": "Stable" | absent}}

    ``rendered_fields`` is the denominator of the extraction-accuracy score
    (spec §18.6); ``gap_fill`` carries the values the template invented, which
    only this module knows and ``expected_writer`` needs. Only the bond
    renderers are instrumented — Bonds is the v1 comparison scope, so a loan
    email reports whatever the shared helpers happened to mark.
    """
    rec = _Recorder()
    _state.rec = rec
    try:
        if tool == "loans":
            subject, body = build_loan_email(payloads, fmt or DEFAULT_LOAN_FORMAT)
        else:
            subject, body = build_bond_email(payloads, fmt or DEFAULT_BOND_FORMAT)
    finally:
        _state.rec = None
    return subject, body, rec.meta()
